/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtectedBuildHistoryRouteImport } from './routes/_protected/build-history'
import { Route as ProtectedFeedbackRouteImport } from './routes/_protected/feedback'
import { Route as ProtectedFriendsRouteImport } from './routes/_protected/friends'
import { Route as ProtectedLibraryRouteImport } from './routes/_protected/library'
import { Route as ProtectedLogRouteImport } from './routes/_protected/log'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSubmitShowRouteImport } from './routes/_protected/submit-show'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ArtistsIdRouteImport } from './routes/artists/$id'
import { Route as ListsIdRouteImport } from './routes/lists/$id'
import { Route as PIdRouteImport } from './routes/p/$id'
import { Route as ShowsSlugRouteImport } from './routes/shows/$slug'
import { Route as VenuesIdRouteImport } from './routes/venues/$id'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedAdminCatalogRouteImport } from './routes/_protected/admin/catalog'
import { Route as ProtectedAdminImportRouteImport } from './routes/_protected/admin/import'
import { Route as ProtectedAdminPeopleRouteImport } from './routes/_protected/admin/people'
import { Route as ProtectedAdminPhotosRouteImport } from './routes/_protected/admin/photos'
import { Route as ProtectedAdminProductionsRouteImport } from './routes/_protected/admin/productions'
import { Route as ProtectedAdminReportsRouteImport } from './routes/_protected/admin/reports'
import { Route as ProtectedAdminShowsRouteImport } from './routes/_protected/admin/shows'
import { Route as ProtectedAdminVenuesRouteImport } from './routes/_protected/admin/venues'
import { Route as ProtectedListsIndexRouteImport } from './routes/_protected/lists/index'
import { Route as ProtectedOutingsIdRouteImport } from './routes/_protected/outings/$id'
import { Route as ProtectedPeopleHandleRouteImport } from './routes/_protected/people/$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBuildHistoryRoute = ProtectedBuildHistoryRouteImport.update({
  id: '/build-history',
  path: '/build-history',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeedbackRoute = ProtectedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFriendsRoute = ProtectedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibraryRoute = ProtectedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLogRoute = ProtectedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSubmitShowRoute = ProtectedSubmitShowRouteImport.update({
  id: '/submit-show',
  path: '/submit-show',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/artists/$id',
  path: '/artists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsSlugRoute = ShowsSlugRouteImport.update({
  id: '/shows/$slug',
  path: '/shows/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIdRoute = VenuesIdRouteImport.update({
  id: '/venues/$id',
  path: '/venues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminCatalogRoute = ProtectedAdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminImportRoute = ProtectedAdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPeopleRoute = ProtectedAdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPhotosRoute = ProtectedAdminPhotosRouteImport.update({
  id: '/admin/photos',
  path: '/admin/photos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminProductionsRoute =
  ProtectedAdminProductionsRouteImport.update({
    id: '/admin/productions',
    path: '/admin/productions',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminReportsRoute = ProtectedAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminShowsRoute = ProtectedAdminShowsRouteImport.update({
  id: '/admin/shows',
  path: '/admin/shows',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminVenuesRoute = ProtectedAdminVenuesRouteImport.update({
  id: '/admin/venues',
  path: '/admin/venues',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedListsIndexRoute = ProtectedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOutingsIdRoute = ProtectedOutingsIdRouteImport.update({
  id: '/outings/$id',
  path: '/outings/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeopleHandleRoute = ProtectedPeopleHandleRouteImport.update({
  id: '/people/$handle',
  path: '/people/$handle',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/build-history': typeof ProtectedBuildHistoryRoute
  '/feedback': typeof ProtectedFeedbackRoute
  '/friends': typeof ProtectedFriendsRoute
  '/library': typeof ProtectedLibraryRoute
  '/log': typeof ProtectedLogRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/submit-show': typeof ProtectedSubmitShowRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/p/$id': typeof PIdRoute
  '/shows/$slug': typeof ShowsSlugRoute
  '/venues/$id': typeof VenuesIdRoute
  '/admin/catalog': typeof ProtectedAdminCatalogRoute
  '/admin/import': typeof ProtectedAdminImportRoute
  '/admin/people': typeof ProtectedAdminPeopleRoute
  '/admin/photos': typeof ProtectedAdminPhotosRoute
  '/admin/productions': typeof ProtectedAdminProductionsRoute
  '/admin/reports': typeof ProtectedAdminReportsRoute
  '/admin/shows': typeof ProtectedAdminShowsRoute
  '/admin/venues': typeof ProtectedAdminVenuesRoute
  '/outings/$id': typeof ProtectedOutingsIdRoute
  '/people/$handle': typeof ProtectedPeopleHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/lists/': typeof ProtectedListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/build-history': typeof ProtectedBuildHistoryRoute
  '/feedback': typeof ProtectedFeedbackRoute
  '/friends': typeof ProtectedFriendsRoute
  '/library': typeof ProtectedLibraryRoute
  '/log': typeof ProtectedLogRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/submit-show': typeof ProtectedSubmitShowRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/p/$id': typeof PIdRoute
  '/shows/$slug': typeof ShowsSlugRoute
  '/venues/$id': typeof VenuesIdRoute
  '/admin/catalog': typeof ProtectedAdminCatalogRoute
  '/admin/import': typeof ProtectedAdminImportRoute
  '/admin/people': typeof ProtectedAdminPeopleRoute
  '/admin/photos': typeof ProtectedAdminPhotosRoute
  '/admin/productions': typeof ProtectedAdminProductionsRoute
  '/admin/reports': typeof ProtectedAdminReportsRoute
  '/admin/shows': typeof ProtectedAdminShowsRoute
  '/admin/venues': typeof ProtectedAdminVenuesRoute
  '/outings/$id': typeof ProtectedOutingsIdRoute
  '/people/$handle': typeof ProtectedPeopleHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/lists': typeof ProtectedListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/build-history': typeof ProtectedBuildHistoryRoute
  '/_protected/feedback': typeof ProtectedFeedbackRoute
  '/_protected/friends': typeof ProtectedFriendsRoute
  '/_protected/library': typeof ProtectedLibraryRoute
  '/_protected/log': typeof ProtectedLogRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/submit-show': typeof ProtectedSubmitShowRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/p/$id': typeof PIdRoute
  '/shows/$slug': typeof ShowsSlugRoute
  '/venues/$id': typeof VenuesIdRoute
  '/_protected/admin/catalog': typeof ProtectedAdminCatalogRoute
  '/_protected/admin/import': typeof ProtectedAdminImportRoute
  '/_protected/admin/people': typeof ProtectedAdminPeopleRoute
  '/_protected/admin/photos': typeof ProtectedAdminPhotosRoute
  '/_protected/admin/productions': typeof ProtectedAdminProductionsRoute
  '/_protected/admin/reports': typeof ProtectedAdminReportsRoute
  '/_protected/admin/shows': typeof ProtectedAdminShowsRoute
  '/_protected/admin/venues': typeof ProtectedAdminVenuesRoute
  '/_protected/outings/$id': typeof ProtectedOutingsIdRoute
  '/_protected/people/$handle': typeof ProtectedPeopleHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/lists/': typeof ProtectedListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/build-history'
    | '/feedback'
    | '/friends'
    | '/library'
    | '/log'
    | '/profile'
    | '/settings'
    | '/submit-show'
    | '/api/health'
    | '/api/uploads'
    | '/artists/$id'
    | '/lists/$id'
    | '/p/$id'
    | '/shows/$slug'
    | '/venues/$id'
    | '/admin/catalog'
    | '/admin/import'
    | '/admin/people'
    | '/admin/photos'
    | '/admin/productions'
    | '/admin/reports'
    | '/admin/shows'
    | '/admin/venues'
    | '/outings/$id'
    | '/people/$handle'
    | '/api/auth/$'
    | '/api/images/$'
    | '/admin/'
    | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/build-history'
    | '/feedback'
    | '/friends'
    | '/library'
    | '/log'
    | '/profile'
    | '/settings'
    | '/submit-show'
    | '/api/health'
    | '/api/uploads'
    | '/artists/$id'
    | '/lists/$id'
    | '/p/$id'
    | '/shows/$slug'
    | '/venues/$id'
    | '/admin/catalog'
    | '/admin/import'
    | '/admin/people'
    | '/admin/photos'
    | '/admin/productions'
    | '/admin/reports'
    | '/admin/shows'
    | '/admin/venues'
    | '/outings/$id'
    | '/people/$handle'
    | '/api/auth/$'
    | '/api/images/$'
    | '/admin'
    | '/lists'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/discover'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/build-history'
    | '/_protected/feedback'
    | '/_protected/friends'
    | '/_protected/library'
    | '/_protected/log'
    | '/_protected/profile'
    | '/_protected/settings'
    | '/_protected/submit-show'
    | '/api/health'
    | '/api/uploads'
    | '/artists/$id'
    | '/lists/$id'
    | '/p/$id'
    | '/shows/$slug'
    | '/venues/$id'
    | '/_protected/admin/catalog'
    | '/_protected/admin/import'
    | '/_protected/admin/people'
    | '/_protected/admin/photos'
    | '/_protected/admin/productions'
    | '/_protected/admin/reports'
    | '/_protected/admin/shows'
    | '/_protected/admin/venues'
    | '/_protected/outings/$id'
    | '/_protected/people/$handle'
    | '/api/auth/$'
    | '/api/images/$'
    | '/_protected/admin/'
    | '/_protected/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ArtistsIdRoute: typeof ArtistsIdRoute
  ListsIdRoute: typeof ListsIdRoute
  PIdRoute: typeof PIdRoute
  ShowsSlugRoute: typeof ShowsSlugRoute
  VenuesIdRoute: typeof VenuesIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/build-history': {
      id: '/_protected/build-history'
      path: '/build-history'
      fullPath: '/build-history'
      preLoaderRoute: typeof ProtectedBuildHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/feedback': {
      id: '/_protected/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof ProtectedFeedbackRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/friends': {
      id: '/_protected/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof ProtectedFriendsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library': {
      id: '/_protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedLibraryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/log': {
      id: '/_protected/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof ProtectedLogRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/submit-show': {
      id: '/_protected/submit-show'
      path: '/submit-show'
      fullPath: '/submit-show'
      preLoaderRoute: typeof ProtectedSubmitShowRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/artists/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$slug': {
      id: '/shows/$slug'
      path: '/shows/$slug'
      fullPath: '/shows/$slug'
      preLoaderRoute: typeof ShowsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$id': {
      id: '/venues/$id'
      path: '/venues/$id'
      fullPath: '/venues/$id'
      preLoaderRoute: typeof VenuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/catalog': {
      id: '/_protected/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof ProtectedAdminCatalogRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/import': {
      id: '/_protected/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof ProtectedAdminImportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/people': {
      id: '/_protected/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof ProtectedAdminPeopleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/photos': {
      id: '/_protected/admin/photos'
      path: '/admin/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof ProtectedAdminPhotosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/productions': {
      id: '/_protected/admin/productions'
      path: '/admin/productions'
      fullPath: '/admin/productions'
      preLoaderRoute: typeof ProtectedAdminProductionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/reports': {
      id: '/_protected/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof ProtectedAdminReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/shows': {
      id: '/_protected/admin/shows'
      path: '/admin/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof ProtectedAdminShowsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/venues': {
      id: '/_protected/admin/venues'
      path: '/admin/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof ProtectedAdminVenuesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/lists/': {
      id: '/_protected/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ProtectedListsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outings/$id': {
      id: '/_protected/outings/$id'
      path: '/outings/$id'
      fullPath: '/outings/$id'
      preLoaderRoute: typeof ProtectedOutingsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people/$handle': {
      id: '/_protected/people/$handle'
      path: '/people/$handle'
      fullPath: '/people/$handle'
      preLoaderRoute: typeof ProtectedPeopleHandleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBuildHistoryRoute: typeof ProtectedBuildHistoryRoute
  ProtectedFeedbackRoute: typeof ProtectedFeedbackRoute
  ProtectedFriendsRoute: typeof ProtectedFriendsRoute
  ProtectedLibraryRoute: typeof ProtectedLibraryRoute
  ProtectedLogRoute: typeof ProtectedLogRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedSubmitShowRoute: typeof ProtectedSubmitShowRoute
  ProtectedAdminCatalogRoute: typeof ProtectedAdminCatalogRoute
  ProtectedAdminImportRoute: typeof ProtectedAdminImportRoute
  ProtectedAdminPeopleRoute: typeof ProtectedAdminPeopleRoute
  ProtectedAdminPhotosRoute: typeof ProtectedAdminPhotosRoute
  ProtectedAdminProductionsRoute: typeof ProtectedAdminProductionsRoute
  ProtectedAdminReportsRoute: typeof ProtectedAdminReportsRoute
  ProtectedAdminShowsRoute: typeof ProtectedAdminShowsRoute
  ProtectedAdminVenuesRoute: typeof ProtectedAdminVenuesRoute
  ProtectedOutingsIdRoute: typeof ProtectedOutingsIdRoute
  ProtectedPeopleHandleRoute: typeof ProtectedPeopleHandleRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedListsIndexRoute: typeof ProtectedListsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBuildHistoryRoute: ProtectedBuildHistoryRoute,
  ProtectedFeedbackRoute: ProtectedFeedbackRoute,
  ProtectedFriendsRoute: ProtectedFriendsRoute,
  ProtectedLibraryRoute: ProtectedLibraryRoute,
  ProtectedLogRoute: ProtectedLogRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedSubmitShowRoute: ProtectedSubmitShowRoute,
  ProtectedAdminCatalogRoute: ProtectedAdminCatalogRoute,
  ProtectedAdminImportRoute: ProtectedAdminImportRoute,
  ProtectedAdminPeopleRoute: ProtectedAdminPeopleRoute,
  ProtectedAdminPhotosRoute: ProtectedAdminPhotosRoute,
  ProtectedAdminProductionsRoute: ProtectedAdminProductionsRoute,
  ProtectedAdminReportsRoute: ProtectedAdminReportsRoute,
  ProtectedAdminShowsRoute: ProtectedAdminShowsRoute,
  ProtectedAdminVenuesRoute: ProtectedAdminVenuesRoute,
  ProtectedOutingsIdRoute: ProtectedOutingsIdRoute,
  ProtectedPeopleHandleRoute: ProtectedPeopleHandleRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedListsIndexRoute: ProtectedListsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ArtistsIdRoute: ArtistsIdRoute,
  ListsIdRoute: ListsIdRoute,
  PIdRoute: PIdRoute,
  ShowsSlugRoute: ShowsSlugRoute,
  VenuesIdRoute: VenuesIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
